timezone: Asia/Seoul
lang: ko

title: "kimzuni"
description: ""
url: "https://kimzuni.com"
baseurl: ""

email: "hello@kimzuni.com"
github: kimzuni

cdn: "https://cdn.jsdelivr.net/gh/kimzuni/cdn/"
favicons: "https://cdn.jsdelivr.net/gh/kimzuni/logo@latest/favicons"



include: ['_pages']

google_analytics:
  id: G-GGDJ40KE4F





sass:
  style: compressed
  sourcemap: never
